spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 971014

  jpa:
    hibernate:
      # 实体类更改会更新表结构
      ddl-auto: update
    # SQL语句输出到控制台和日志文件
    show-sql: true

# 日志级别
logging:
  level:
    root: info
    com.lianghd: debug
  file:
    path: log/myblog-dev.log
